---
sudo: required
dist: trusty

language: python
python: "2.7"

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
env:
  - ANSIBLE_VERSION=2.7




before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==$ANSIBLE_VERSION
  - pip install ansible-lint

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i inventory plays/main.yml --syntax-check
  - ansible-lint plays/main.yml
