# AWS playbook
---
- hosts: localhost
  connection: local
  gather_facts: False


  tasks:
    - name: Generate Temporary key
      openssh_keypair:
        path: /tmp/id_ssh_rsa
        size: 2048
        mode: 400
      register: tmp_key

    - name: Provisioning EC2 instances
      block:
      - name: Upload public key to AWS
        ec2_key:
          name: "{{ key_name }}"
          key_material: "{{ tmp_key.public_key }}"
          region: "{{ region }}"
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          
      - name: Create security group
        ec2_group:
          name: "{{ sec_group }}"
          description: "Sec group for app {{ id }}"
          region: "{{ region }}"
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          rules:
            - proto: tcp
              ports:
                - 22
              cidr_ip: ***
              rule_desc: allow all on ssh port
        register: result_sec_group

      - name: Provision instances
        ec2:
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          key_name: "{{ key_name }}"
          id: "{{ id }}"
          group_id: "{{ result_sec_group.group_id }}"
          image: "{{ image }}"
          instance_type: t2.micro
          region: "{{ region }}"
          wait: true
          count: 2
        register: ec2

      - name: Add created instances in hosts
        add_host:
          name: "{{ item.public_ip }}"
          groups: webservers
        with_items: "{{ ec2.instances }}"
